### ISSUE TITLE
 No value present

### ISSUE THREAD

**Issue by mercadanteus** [NoahBPeterson/BlockTrack#3]
Hello, I have many bug reports like this:

* Nukkit Version: git-3571621 
* Java Version: Java HotSpot(TM) 64-Bit Server VM (1.8.0_251-b08)

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | Linux-amd64 [4.15.0-88-generic] |  
| Memory(RAM) | 270.4 GB | 
| Storage Size | 475.3 GB | 
| Storage Type | Disk 0:(avail=436.8 GB, total=475.3 GB)  | 
| CPU Type | UNKNOWN | 
| CPU Core Count | 24 | 

### Crashdump, Backtrace or Other Files

```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.nbpe.blocktrack.BlockTrack.blockHistoryFormat(BlockTrack.java:173)
	at com.nbpe.blocktrack.BlockHistoryCommand.blockHistorySend(BlockHistoryCommand.java:38)
	at com.nbpe.listeners.async.AsyncBlockSend.onRun(AsyncBlockSend.java:22)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by NoahBPeterson** [comment]
What version of BlockTrack are you using?

**Comment by mercadanteus** [comment]
Sorry for the delay, BE server version §bv1.16.0§r, is the latest master branch

**Comment by ghost** [comment]
This error sometimes appears, when you try to get the blockhistory of a block, that hasn't a history.
