### ISSUE TITLE
Erron in database

### ISSUE THREAD

**Issue by mercadanteus** [NoahBPeterson/BlockTrack#5]
Hello, not sure what to to about this, maybe purge the database? any help is appreciated
https://hastebin.com/ojumawatos.sql

**Comment by NoahBPeterson** [comment]
If it keeps happening, that could fix it. Let me know if it does. Back up your database just in case it doesn't work.

**Comment by mercadanteus** [comment]
It did´nt worked, this is how looks the log, is filled with error msgs:  https://hastebin.com/cexicurosi.apache

**Comment by NoahBPeterson** [comment]
I’ll be sure to check it out

**Comment by NoahBPeterson** [comment]
Did you update to the latest version of the plugin? It looks like your line numbers are wrong for the latest version of the code.

**Comment by mercadanteus** [comment]
> Did you update to the latest version of the plugin? It looks like your line numbers are wrong for the latest version of the code.

I´m using last version published here https://cloudburstmc.org/resources/blocktrack.477/
 
Here is a detail of errors I get when usin 1.0.2 and 1.0.3  https://hastebin.com/gicowecena.sql

**Comment by NoahBPeterson** [comment]
I have no idea what's causing this. I've added some debug statements here: http://uppit.com/64uu0gczcuh8

Try this one, and get back to me with the error messages it prints out.

**Comment by mercadanteus** [comment]
> I have no idea what's causing this. I've added some debug statements here: http://uppit.com/64uu0gczcuh8
> 
> Try this one, and get back to me with the error messages it prints out.

Thanks for take the time!  Is this the info you mean? in console:

2021-06-26 17:24:57.977 [Nukkit Asynchronous Task Handler #24] INFO  - [BlockTrack] Failed to save record! 01S00
2021-06-26 17:24:58.004 [Nukkit Asynchronous Task Handler #24] INFO  - [BlockTrack] Failed to save record! 01S00
2021-06-26 17:24:58.042 [Nukkit Asynchronous Task Handler #21] INFO  - [BlockTrack] Failed to save record! 01S00
2021-06-26 17:24:58.063 [Nukkit Asynchronous Task Handler #21] FATAL - Exception in asynchronous task
java.lang.NullPointerException: null
	at com.nbpe.listeners.async.AsyncBuild.onRun(AsyncBuild.java:37) ~[BlockTrack-1.0.4.jar:1.0.4]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[custom.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

**Comment by NoahBPeterson** [comment]
Could you use /blockHistory and give me the errors from that?

**Comment by mercadanteus** [comment]
> Could you use /blockHistory and give me the errors from that?

Here is https://hastebin.com/quwemuzegi.yaml

**Comment by NoahBPeterson** [comment]
It looks like a timezone issue? This is unexpected, but the error is happening in the database itself. Thank you for sticking with me.

**Comment by mercadanteus** [comment]
I ask for help with the host some days ago and they told me:
"This appears to be a configuration issue with something using the MySQL database. Were any plugins set up or configured around the time it began? One that a timezone was set in?"
Maybe your plugin is configured for other part of the world time zone?, my server is in Miami

**Comment by NoahBPeterson** [comment]
I don't see any time zone configuration in my plugin or in the database plugin. Try changing your timezone to UTC.
